#ifndef PHASORFILTER_CONF_H
#define PHASORFILTER_CONF_H

#define BUFFER_SIZE 8

#define DFT_SIZE BUFFER_SIZE
#define HCDFT_SIZE BUFFER_SIZE
#define COSINE_FILTER_SIZE BUFFER_SIZE + BUFFER_SIZE / 4
#define SINE_FILTER_SIZE BUFFER_SIZE + BUFFER_SIZE / 4

#endif